packageExtensions:
  cdktf@*:
    dependencies:
      constructs: "*"
  cdktf-cli@*:
    dependencies:
      '@cdktf/node-pty-prebuilt-multiarch': '0.10.1-pre.10'
  prettier-plugin-organize-imports@*:
    dependencies:
      prettier: "*"
      typescript: "*"
