packageExtensions:
  "@cdktf/hcl-tools@*":
    dependencies:
      fs-extra: "*"
  "@cdktf/provider-generator@*":
    dependencies:
      jsii: "*"
      jsii-pacmak: "*"
  cdktf@*:
    dependencies:
      constructs: "*"
  cdktf-cli@*:
    dependencies:
      "@cdktf/node-pty-prebuilt-multiarch": 0.10.1-pre.11
  prettier-plugin-organize-imports@*:
    dependencies:
      prettier: "*"
      typescript: "*"
